# Generated by Django 4.2.3 on 2024-09-06 10:04

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', unique=True)),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('image1', models.ImageField(upload_to='AboutUs')),
                ('image2', models.ImageField(upload_to='About')),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='AboutVisa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('logo', models.ImageField(upload_to='AboutVisa')),
                ('title', models.CharField(max_length=300)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_visa', to='aboutus.aboutus')),
            ],
            options={
                'verbose_name': 'Mission | Vision',
                'verbose_name_plural': 'Mission | Vision',
            },
        ),
        migrations.CreateModel(
            name='Homescreen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='homescreen')),
                ('title', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='VisaPoints',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('point', models.CharField(max_length=700)),
                ('about_visa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_points', to='aboutus.aboutvisa')),
            ],
            options={
                'verbose_name': 'List Mission | Vision',
                'verbose_name_plural': 'List Mission | Vision',
            },
        ),
    ]
