# Generated by Django 5.0.6 on 2024-09-05 11:14

import autoslug.fields
import ckeditor.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_holidayspackages_mapurl_holidayspackages_pdfmanual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidaysPackagesType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('ordering', models.PositiveBigIntegerField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='holidaypackagestype')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.RemoveField(
            model_name='holidayspackagescategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='holidayspackagescategory',
            name='equipment',
        ),
        migrations.AddField(
            model_name='holidayspackages',
            name='equipment',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holidayspackages',
            name='select_package_type',
            field=models.CharField(choices=[('International', 'International'), ('Domestic', 'Domestic')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='holidayspackages',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='packages.holidayspackagescategory'),
        ),
        migrations.AlterField(
            model_name='holidayspackages',
            name='description',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='holidayspackages',
            name='meals',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('All', 'All')], max_length=255),
        ),
        migrations.AddField(
            model_name='holidayspackages',
            name='packagetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packagecategories', to='packages.holidayspackagestype'),
        ),
        migrations.AddField(
            model_name='holidayspackagescategory',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='packages.holidayspackagestype'),
        ),
    ]
