# Generated by Django 5.0.6 on 2024-09-05 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_alter_holidayspackages_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayspackagescomments',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holidayspackagescomments',
            name='rating',
            field=models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
