# Generated by Django 5.0.6 on 2024-09-05 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_holidayspackagescomments_approve_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holidayspackagesgallery',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='holidayspackagesvideos',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='holidayspackagesgallery',
            name='ordering',
        ),
        migrations.RemoveField(
            model_name='holidayspackagesvideos',
            name='ordering',
        ),
    ]
