# Generated by Django 5.0.6 on 2024-09-06 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0011_alter_holidayspackagesfaq_package'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holidayspackagesdates',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterModelOptions(
            name='holidayspackagesitinerary',
            options={'ordering': ['day']},
        ),
        migrations.RemoveField(
            model_name='holidayspackagesdates',
            name='ordering',
        ),
        migrations.RemoveField(
            model_name='holidayspackagesitinerary',
            name='ordering',
        ),
    ]
