# Generated by Django 5.0.6 on 2024-09-09 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
        ('packages', '0014_countries_select_package_type'),
        ('packagestype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidayspackages',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citypackages', to='country.cities'),
        ),
        migrations.AlterField(
            model_name='holidayspackages',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countrypackages', to='country.countries'),
        ),
        migrations.RemoveField(
            model_name='holidayspackagescategory',
            name='type',
        ),
        migrations.AlterField(
            model_name='holidayspackages',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='packagestype.holidayspackagescategory'),
        ),
        migrations.RemoveField(
            model_name='holidayspackagescomments',
            name='package',
        ),
        migrations.RemoveField(
            model_name='holidayspackagescomments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='holidayspackagesgallery',
            name='package',
        ),
        migrations.RemoveField(
            model_name='holidayspackagesitinerary',
            name='package',
        ),
        migrations.RemoveField(
            model_name='packagesmeals',
            name='itinerary',
        ),
        migrations.RemoveField(
            model_name='packagesactivities',
            name='itinerary',
        ),
        migrations.RemoveField(
            model_name='packagesaccommodation',
            name='itinerary',
        ),
        migrations.AlterField(
            model_name='holidayspackages',
            name='packagetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packagecategories', to='packagestype.holidayspackagestype'),
        ),
        migrations.RemoveField(
            model_name='holidayspackagesvideos',
            name='package',
        ),
        migrations.RemoveField(
            model_name='packagesaccommodation',
            name='packages',
        ),
        migrations.RemoveField(
            model_name='packagesactivities',
            name='packages',
        ),
        migrations.RemoveField(
            model_name='packagesmeals',
            name='packages',
        ),
        migrations.DeleteModel(
            name='Cities',
        ),
        migrations.DeleteModel(
            name='Countries',
        ),
        migrations.DeleteModel(
            name='HolidaysPackagesCategory',
        ),
        migrations.DeleteModel(
            name='HolidaysPackagesComments',
        ),
        migrations.DeleteModel(
            name='HolidaysPackagesGallery',
        ),
        migrations.DeleteModel(
            name='HolidaysPackagesItinerary',
        ),
        migrations.DeleteModel(
            name='HolidaysPackagesType',
        ),
        migrations.DeleteModel(
            name='HolidaysPackagesVideos',
        ),
        migrations.DeleteModel(
            name='PackagesAccommodation',
        ),
        migrations.DeleteModel(
            name='PackagesActivities',
        ),
        migrations.DeleteModel(
            name='PackagesMeals',
        ),
    ]
