# Generated by Django 5.0.6 on 2024-09-09 05:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0015_alter_holidayspackages_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidaysPackagesGallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='holidaypackagesgallery')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='packages.holidayspackages')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
